services:

  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=compose-postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U compose-postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./solarwatch_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GEOCODING_KEY=${GEOCODING_API_KEY}
      - MECSBALINT_APP_JWTSECRET=${DEFAULT_JWT_SECRET}
      - MECSBALINT_APP_JWTEXPIRATIONMS=${DEFAULT_JWT_EXPIRATION_MS}

  frontend:
    build: 
      context: ./solarwatch_frontend
    depends_on:
      - backend
    ports:
      - 5173:80
